server:
  port: 8989
  address: 0.0.0.0

spring:
  application:
    name: PROJECT0

  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DB_URI}
    username: ${DB_NAME}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true


frontend:
  url: ${FRONTEND_END_POINT}
cloudinary:
 cloud-name: ${CLOUDINARY_CLOUD_NAME}
 api-key: ${CLOUDINARY_API_KEY}
 api-secret: ${CLOUDINARY_API_SECRET}
