server:
  port: 8989
  address: 0.0.0.0

spring:
  application:
    name: PROJECT0

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/project0
    username: root
    password: Vishal@4545

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

file:
 upload-dir: uploads